### ISSUE TITLE
Add Guix Emacs functionality

### ISSUE THREAD

**Issue by matthewbauer** [matthewbauer/nix-mode#4]
Guix has lots of Emacs scripts. Some of it may be reusable in nix-mode.

http://git.savannah.gnu.org/cgit/guix.git/tree/emacs
https://www.gnu.org/software/guix/manual/html_node/Emacs-Interface.html
# Tasks
- [ ] ~package management mode~
  - [ ] ~package list buffer~
  - [ ] ~package description buffer~
- [x] prettify mode
- [x] build log mode
- [ ] ~shell completion~
- [x] hydra mode
